### ISSUE TITLE
Collect example metrics data set from Prometheus

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/operate-first-openshift-data#1]
As a data scientists I would like to see an example of the metrics generated by the Operate First MOC cluster and stored in the Prometheus instance so that I can gain a better understanding of the kind of data available to me for further analysis.

Acceptance Criteria:

- [ ] Example data set of 5 metrics over a 3 day period in the `data/raw` directory.
- [ ] Notebook showing how to access and collect metrics.

**Comment by tumido** [comment]
Related to https://github.com/operate-first/support/issues/99
