### ISSUE TITLE
wrong prometheus URL

### ISSUE THREAD

**Issue by durandom** [aicoe-aiops/operate-first-openshift-data#7]
the prometheus URL in https://github.com/aicoe-aiops/operate-first-openshift-data/blob/master/notebooks/operate_first_metrics.ipynb seems to be wrong

cc @4n4nd

**Comment by 4n4nd** [comment]
The new Prometheus url is: http://prometheus-portal-opf-monitoring.apps.zero.massopen.cloud/

**Comment by 4n4nd** [comment]
We might want to access Thanos instead http://thanos-query-frontend-opf-observatorium.apps.zero.massopen.cloud/
Related https://github.com/operate-first/support/issues/127

**Comment by 4n4nd** [comment]
I think this issue can be closed now

**Comment by MichaelClifford** [comment]
Thanks @4n4nd. Closing
