### ISSUE TITLE
Notebook for events

### ISSUE THREAD

**Issue by durandom** [aicoe-aiops/operate-first-openshift-data#8]
Is there a way to capture a stream of events from openshift from the CLI?
Like `oc get events --streaming --format .json` ?

Can we have a set of e.g. 1hr events captured in here?

cc @tumido

**Comment by tumido** [comment]
The proper command would be:
```
oc get events --watch -o json
```

**Comment by MichaelClifford** [comment]
I think someone who is cluster admin would need to collect this event data. I don't think the projects I have access to are generating any events.  

![image](https://user-images.githubusercontent.com/4494906/111361120-e530d880-8663-11eb-9ba9-6d35602288af.png)

**Comment by tumido** [comment]
@MichaelClifford  ok, I can generate a file for you... :)
